<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>12-2</title>
</head>

<body>
  <p>open console!!</p>
  <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/3.1.2/rx.all.min.js"></script>
  <script>
    // 一割の確率でエラーを返す非同期処理
    function myPromise(data, ms) {
      const d = $.Deferred();

      setTimeout(() => {
        if (Math.random() > 0.1) {
          d.resolve(data);
        } else {
          d.reject('Error');
        }
      }, ms);

      return d;
    }

    const item = [{ type: 'A' }, { type: 'B' }, { type: 'C' }, { type: 'D' }, { type: 'F' }];

    // 非同期処理が全てを完了したら値を流す。
    // エラーが発生した場合 error イベントは発火する。
    // そのため、一つでもエラーが発生した場合、成功したデータは流れない。
    Rx.Observable
      .of(item)
      .flatMap(v => Rx.Observable.forkJoin(
        v.map((v, index) => myPromise(v, index * 1000))
      ))
      .subscribe(
        v => console.log(v),
        error => console.log(error),
        () => console.log('--- completed!!! ---')
      );
    // 全て非同期処理が成功した場合、以下の出力
    // [{ type: 'A' }, { type: 'B' }, { type: 'C' }, { type: 'D' }, { type: 'F' }];
    // --- completed!!! ---
    //
    // エラーの場合は以下の出力
    // "Error"
  </script>
</body>

</html>
